# Generated by Django 5.0.6 on 2024-05-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('item', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
