# Generated by Django 5.0.6 on 2024-05-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='item',
        ),
        migrations.AddField(
            model_name='produce',
            name='items',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
